### ISSUE TITLE
HTML Form Exercise

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/html_repository#1]
https://www.dropbox.com/s/utlctf92duufwyw/form.png is the URL of a Image (Form Image). You need to convert this image to an HTML form.

https://github.com/wilsonokibe/html_repository/blob/master/form.html

**Comment by segunadeleye** [comment]
1. Why are you using `<table>` tags for layout, use something different. Moreover, two `<td>` tags are outside the table tag.
2. Can you use a different tag for "Your name", "Email", Phone Number, etc
3. The `<b>` tags should not be used. Use something else. Deprecated tags should not be used.
4. You don't have to use the suffix "_name" for the names of the form fields.
5. No radio button should be checked by default
6. I Like: For the multiple select field, Make the options appear all I want. I don't want to have to scroll.
7. Remove extra white spaces and use proper indentation.
8. Why `method="GET"`?
9. Can you use something else instead of the `<p>` tags
10. Why are you passing empty string to the value attribute? Do you need to set it to make the field empty by default?

**Comment by segunadeleye** [comment]
1. Remove empty CSS style.
2. There is no need to set the input value to empty string.
3. Use appropriate form method.
4. Fix indentation
5. Remove all "_name".

**Comment by wilsonokibe** [comment]
1. Empty CSS removed.
2. All input value with empty string removed.
3. Use of POST method for secure data retrieval instead of GET method
4. Indentation fixed
5. All "_name" removed.

**Comment by segunadeleye** [comment]
All fine now
